server:
  port: 8085

spring:
  application:
    name: HOTEL-SERVICE
    

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  cloud:
    config:
      enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect