server:
  port: 8080
  
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false 
      serviceUrl.defaultZone: http://location:8080/eureka/
   server:
    waitTimeInMsWhenSyncEmpty: 0
   instance:
     hostname: localhost
    
   